// Source: Compiled from RealGM & Tankathon (Current as of 2025-26 Season)
export const TEAM_ASSETS = {
  // --- THE ASSET KINGS (Teams with tons of picks) ---
  SAS: [
    { year: 2026, round: 1, from: "Own", notes: "" },
    { year: 2026, round: 1, from: "ATL", notes: "Unprotected" },
    { year: 2026, round: 2, from: "Own", notes: "" },
    { year: 2026, round: 2, from: "LAL", notes: "via IND (Protected 31-55)" },
    { year: 2027, round: 1, from: "Own", notes: "" },
    { year: 2027, round: 1, from: "ATL", notes: "Unprotected" },
    { year: 2028, round: 1, from: "Own", notes: "" },
    { year: 2028, round: 1, from: "BOS", notes: "Protected 1 (Swap)" },
    { year: 2029, round: 1, from: "Own", notes: "" },
    { year: 2030, round: 1, from: "Own", notes: "" },
    { year: 2030, round: 1, from: "DAL", notes: "Pick Swap" },
    { year: 2031, round: 1, from: "Own", notes: "" },
    { year: 2031, round: 1, from: "SAC", notes: "Swap Rights" },
  ],
  OKC: [
    { year: 2026, round: 1, from: "Own", notes: "" },
    { year: 2026, round: 1, from: "HOU", notes: "Protected 1-4" },
    { year: 2026, round: 1, from: "LAC", notes: "Unprotected" },
    { year: 2027, round: 1, from: "Own", notes: "" },
    { year: 2027, round: 1, from: "DEN", notes: "Protected 1-5" },
    { year: 2028, round: 1, from: "Own", notes: "" },
    { year: 2029, round: 1, from: "Own", notes: "" },
    { year: 2029, round: 1, from: "DEN", notes: "Protected 1-5" },
  ],
  BKN: [
    { year: 2026, round: 1, from: "Own", notes: "" },
    { year: 2026, round: 1, from: "PHX", notes: "Unprotected" },
    { year: 2026, round: 1, from: "MIL", notes: "Protected 1-4" },
    { year: 2027, round: 1, from: "Own", notes: "" },
    { year: 2027, round: 1, from: "PHX", notes: "Unprotected" },
    { year: 2027, round: 1, from: "PHI", notes: "Protected 1-8" },
    { year: 2028, round: 1, from: "Own", notes: "" },
    { year: 2029, round: 1, from: "Own", notes: "" },
    { year: 2029, round: 1, from: "PHX", notes: "Unprotected" },
    { year: 2029, round: 1, from: "DAL", notes: "Unprotected" },
  ],
  UTA: [
    { year: 2026, round: 1, from: "Own", notes: "" },
    { year: 2026, round: 1, from: "MIN", notes: "Unprotected" },
    { year: 2026, round: 1, from: "CLE", notes: "Unprotected" },
    { year: 2027, round: 1, from: "Own", notes: "" },
    { year: 2027, round: 1, from: "MIN", notes: "Unprotected" },
    { year: 2027, round: 1, from: "CLE", notes: "Unprotected" },
    { year: 2028, round: 1, from: "Own", notes: "" },
    { year: 2029, round: 1, from: "Own", notes: "" },
    { year: 2029, round: 1, from: "MIN", notes: "Protected 1-5" },
  ],
  NYK: [
    { year: 2026, round: 1, from: "Own", notes: "" },
    { year: 2026, round: 1, from: "WAS", notes: "Protected 1-8" },
    { year: 2026, round: 1, from: "MIL", notes: "Protected 1-4" },
    { year: 2027, round: 1, from: "Own", notes: "" },
    { year: 2027, round: 1, from: "DET", notes: "Protected 1-9" },
  ],
  
  // --- THE REST (Standard "Own" Picks + Common Swaps) ---
  ATL: [{ year: 2026, round: 1, from: "Own", notes: "" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  BOS: [{ year: 2026, round: 1, from: "Own", notes: "" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  CHA: [{ year: 2026, round: 1, from: "Own", notes: "" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  CHI: [{ year: 2026, round: 1, from: "Own", notes: "Owed to SAS (Top 8 Prot)" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  CLE: [{ year: 2026, round: 1, from: "Own", notes: "Owed to UTA" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  DAL: [{ year: 2026, round: 1, from: "Own", notes: "" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  DEN: [{ year: 2026, round: 1, from: "Own", notes: "" }, { year: 2027, round: 1, from: "Own", notes: "Owed to OKC (Top 5 Prot)" }],
  DET: [{ year: 2026, round: 1, from: "Own", notes: "" }, { year: 2027, round: 1, from: "Own", notes: "Owed to NYK (Top 9 Prot)" }],
  GSW: [{ year: 2026, round: 1, from: "Own", notes: "" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  HOU: [{ year: 2026, round: 1, from: "Own", notes: "Owed to OKC (Top 4 Prot)" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  IND: [{ year: 2026, round: 1, from: "Own", notes: "" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  LAC: [{ year: 2026, round: 1, from: "Own", notes: "Owed to OKC" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  LAL: [{ year: 2026, round: 1, from: "Own", notes: "" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  MEM: [{ year: 2026, round: 1, from: "Own", notes: "" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  MIA: [{ year: 2026, round: 1, from: "Own", notes: "" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  MIL: [{ year: 2026, round: 1, from: "Own", notes: "Owed to NOP/NYK" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  MIN: [{ year: 2026, round: 1, from: "Own", notes: "Owed to UTA" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  NOP: [{ year: 2026, round: 1, from: "Own", notes: "" }, { year: 2026, round: 1, from: "MIL", notes: "Protected 1-4" }],
  ORL: [{ year: 2026, round: 1, from: "Own", notes: "" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  PHI: [{ year: 2026, round: 1, from: "Own", notes: "Owed to OKC (Top 6 Prot)" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  PHX: [{ year: 2026, round: 1, from: "Own", notes: "Owed to BKN" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  POR: [{ year: 2026, round: 1, from: "Own", notes: "" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  SAC: [ // The User's Reference
    { year: 2026, round: 1, from: "Own", notes: "" },
    { year: 2026, round: 2, from: "Own", notes: "" },
    { year: 2026, round: 2, from: "CHA", notes: "Protected 56-60" },
    { year: 2027, round: 1, from: "Own", notes: "" },
    { year: 2027, round: 1, from: "SAS", notes: "Protected 17-30" }, 
    { year: 2027, round: 2, from: "CHA", notes: "No protections" },
    { year: 2031, round: 1, from: "MIN", notes: "No protections" },
  ],
  TOR: [{ year: 2026, round: 1, from: "Own", notes: "" }, { year: 2027, round: 1, from: "Own", notes: "" }],
  WAS: [{ year: 2026, round: 1, from: "Own", notes: "" }, { year: 2027, round: 1, from: "Own", notes: "" }],
};
